/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reservI ced.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timer.h"
#include "servo.h"
#include "one_shot.h"
#include "stm32f303xc.h"

volatile uint32_t timer_count = 0;

void my_timer_callback(void) {
    timer_count++;
}

void my_oneshot_callback(void) {
    timer_count = 0;
}

int main(void)
{
    timer_init(500, my_timer_callback);
    servo_init(GPIOA, (1 << 8));
    servo_set_position(0.5);
    oneshot_start(3000, my_oneshot_callback);

    for(;;);
}

